import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "Terms of Service | Gyaan Mitra",
  description: "Terms of Service for Gyaan Mitra — the rules governing your use of our platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />

      <section className="bg-secondary py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-extrabold text-white">Terms of Service</h1>
          <p className="mt-2 text-secondary-200 text-sm">Last updated: May 2026</p>
        </div>
      </section>

      <section className="flex-1 bg-gray-50 py-12 px-4">
        <div className="max-w-3xl mx-auto space-y-8">
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-8 py-8 prose prose-sm max-w-none text-gray-700 leading-relaxed">

            <h2 className="text-lg font-bold text-secondary mt-0 mb-3">1. Acceptance of Terms</h2>
            <p>By using Gyaan Mitra (&quot;Service&quot;), operated by <strong>USD Vision AI LLP</strong>, you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">2. Description of Service</h2>
            <p>Gyaan Mitra is an AI-powered platform that helps teachers create lesson plans, worksheets, and exam papers. Generated content is powered by Claude AI (Anthropic) and is provided for educational purposes.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">3. Eligibility</h2>
            <p>You must be at least 18 years old to create an account. The Service is intended for use by teachers, educators, and educational institutions. By using the Service, you represent that you meet these requirements.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">4. Free and Premium Plans</h2>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li><strong>Free plan:</strong> Up to 5 AI generations per month. No credit card required.</li>
              <li><strong>Premium plan:</strong> Unlimited generations. Billed annually. Pricing is displayed at checkout.</li>
              <li>We reserve the right to change pricing with reasonable notice.</li>
            </ul>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">5. Acceptable Use</h2>
            <p>You agree to use Gyaan Mitra only for lawful, educational purposes. You must not:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the Service to generate content that is harmful, deceptive, or violates applicable law.</li>
              <li>Upload files containing personal data of students, exam answers you do not own, or copyrighted material without authorisation.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the platform or its APIs.</li>
              <li>Share your account credentials with others.</li>
              <li>Use the Service to create exam papers for commercial resale without our written permission.</li>
            </ul>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">6. AI-Generated Content</h2>
            <p>Content generated by Gyaan Mitra is produced by AI and may contain errors, inaccuracies, or outdated information. You are responsible for reviewing and verifying all generated content before using it in a classroom or educational setting. We do not guarantee the accuracy, completeness, or curriculum alignment of AI-generated output.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">7. Intellectual Property</h2>
            <p>Content you generate using Gyaan Mitra belongs to you. You grant us a limited licence to store and display your content solely to provide the Service. The Gyaan Mitra platform, brand, and underlying technology are owned by USD Vision AI LLP.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">8. Refunds</h2>
            <p>Premium plan payments are non-refundable except where required by applicable law. If you experience a billing error, contact us at <strong>hello@gyaanmitra.com</strong> within 7 days.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">9. Termination</h2>
            <p>We may suspend or terminate your account if you violate these Terms. You may delete your account at any time from Settings. Upon termination, your saved content will be deleted after 30 days.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">10. Disclaimer of Warranties</h2>
            <p>Gyaan Mitra is provided &quot;as is&quot; without warranties of any kind. We do not guarantee uninterrupted access or that the Service will be error-free. To the extent permitted by law, we disclaim all implied warranties.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">11. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, USD Vision AI LLP shall not be liable for any indirect, incidental, or consequential damages arising from your use of Gyaan Mitra. Our total liability shall not exceed the amount you paid us in the preceding 12 months.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">12. Governing Law</h2>
            <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">13. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes via email or a notice on the website. Continued use of the Service after changes constitutes your acceptance.</p>

            <h2 className="text-lg font-bold text-secondary mt-8 mb-3">14. Contact</h2>
            <p>
              <strong>USD Vision AI LLP</strong><br />
              Email: <strong>hello@gyaanmitra.com</strong>
            </p>
          </div>

          <p className="text-center text-sm text-gray-400">
            Also see our{" "}
            <Link href="/privacy-policy" className="text-primary font-medium hover:underline">Privacy Policy</Link>
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
